# GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_dev
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Isrc
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),release_dev)
TARGETDIR = bin/Dev/Release
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/Dev/Release/test_runner
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra
LIBS += bin/Dev/Release/libget_next_line.a
LDDEPS += bin/Dev/Release/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_42)
TARGETDIR = bin/42/Release
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/42/Release/test_runner
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu
LIBS += bin/42/Release/libget_next_line.a
LDDEPS += bin/42/Release/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 --target=x86_64-linux-gnu -fuse-ld=lld

else ifeq ($(config),debug1b_dev)
TARGETDIR = bin/Dev/Debug1b
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/Dev/Debug1b/test_runner
DEFINES += -DBUFFER_SIZE=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
LIBS += bin/Dev/Debug1b/libget_next_line.a
LDDEPS += bin/Dev/Debug1b/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug1b_42)
TARGETDIR = bin/42/Debug1b
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/42/Debug1b/test_runner
DEFINES += -DBUFFER_SIZE=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
LIBS += bin/42/Debug1b/libget_next_line.a
LDDEPS += bin/42/Debug1b/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 --target=x86_64-linux-gnu -fuse-ld=lld

else ifeq ($(config),debug10b_dev)
TARGETDIR = bin/Dev/Debug10b
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/Dev/Debug10b/test_runner
DEFINES += -DBUFFER_SIZE=10
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
LIBS += bin/Dev/Debug10b/libget_next_line.a
LDDEPS += bin/Dev/Debug10b/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug10b_42)
TARGETDIR = bin/42/Debug10b
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/42/Debug10b/test_runner
DEFINES += -DBUFFER_SIZE=10
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
LIBS += bin/42/Debug10b/libget_next_line.a
LDDEPS += bin/42/Debug10b/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 --target=x86_64-linux-gnu -fuse-ld=lld

else ifeq ($(config),debug1mb_dev)
TARGETDIR = bin/Dev/Debug1mb
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/Dev/Debug1mb/test_runner
DEFINES += -DBUFFER_SIZE=1000000
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Wall -Werror -Wextra -g
LIBS += bin/Dev/Debug1mb/libget_next_line.a
LDDEPS += bin/Dev/Debug1mb/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug1mb_42)
TARGETDIR = bin/42/Debug1mb
TARGET = $(TARGETDIR)/test_runner
OBJDIR = obj/42/Debug1mb/test_runner
DEFINES += -DBUFFER_SIZE=1000000
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wall -Werror -Wextra --target=x86_64-linux-gnu -g
LIBS += bin/42/Debug1mb/libget_next_line.a
LDDEPS += bin/42/Debug1mb/libget_next_line.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 --target=x86_64-linux-gnu -fuse-ld=lld

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/main.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking test_runner
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning test_runner
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/main.o: tests/main.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif