start: Call GNL{
  shape: oval
}


delim: Seek delim {
  buf?: |c
    // Buffer left to seek?
     (rd_pos != rd_end)
  | {
    shape: diamond
  }

  read : Read operations{  
    read: Read from file descriptor

    success?: Read successful? { shape: diamond }
    
    mem: Ensure space for read {
      enough?: |c
          // enough memory left to read
          (space >= BUFFER_SIZE)
      | {
         shape: diamond
      }

      expand: {
        tempcpy: Copy to temp {
          cp: Copy to temp
          success?: Copy successful? { shape: diamond }
        }
        freeold: free main buffer
        increase:{          
          reserve: malloc new space
          success?: Reservation successful? { shape: diamond }
        }
        temp_getfrom: get from temp
  
      }
    }
  }
  
  

  seek: Seek delimiter{
    shape: rectangle
  }

  found?: Found delimiter?{
    shape: diamond
  }

}

end: Return String { shape: oval }

abort: Return NULL { shape: oval }

start -> delim.buf?

delim.buf? -> delim.seek: yes
delim.buf? -> delim.read.mem.enough?: no

delim.read.mem.enough? -> delim.read.read: yes, break
delim.read.read -> delim.read.success?
delim.read.success? -> delim.seek: yes
delim.read.success? -> abort: no


delim.read.mem.enough? -> delim.read.mem.expand.tempcpy.cp: no
delim.read.mem.expand.tempcpy.cp-> delim.read.mem.expand.tempcpy.success?
delim.read.mem.expand.tempcpy.success? -> delim.read.mem.expand.freeold: yes
delim.read.mem.expand.tempcpy.success? -> abort : no, break

delim.read.mem.expand.freeold -> delim.read.mem.expand.increase.reserve
delim.read.mem.expand.increase.reserve -> delim.read.mem.expand.increase.success?
delim.read.mem.expand.increase.success? -> delim.read.mem.expand.temp_getfrom : yes
delim.read.mem.expand.increase.success? -> abort : no, break

delim.read.mem.expand.temp_getfrom -> delim.read.mem.enough?

delim.seek -> delim.found?
delim.found? -> delim.buf?: no

delim.found? -> end: yes, break
